### ISSUE TITLE
make double number line the full width of the screen?

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/unit-rates#140] opened 2017-01-24 05:37 UTC
No matter what I've tried, we're going to have serious usability problems caused by markers colliding and overlapping in the double number line. We discussed dynamically adjusting font size, etc. to alleviate this.  But there is no magic that I'm going to be able to work to solve this problem.  The single biggest thing we could do to alleviate this problem is to make the double number line wider. 

In https://github.com/phetsims/unit-rates/issues/139#issuecomment-274710020, I realized that we can make the double number line the full width of the screen in the Shopping Lab screen, because there's currently nothing to the right of it. And the reason why we probably haven't done that is because we want the double number line on the Shopping and Shopping Lab screens to be similar.   

Is there some way that we could change the layout of the Shopping screen, so that we could make the double number line wider there too?

Here's a possibility:

![screenshot_284](https://cloud.githubusercontent.com/assets/3046552/22235089/9243fc26-e1ba-11e6-84ce-626301ffb5bb.png)

The height of the double number line shrunk by modifying the marker editor -- I moved the edit buttons to the sides of the value fields. This change may not be absolutely necessary, but is similar to the placement of the edit buttons in the Questions panel.   

What would be absolute necessary is reducing the height of the Questions panel. And that obviously involves making some compromises in the Questions panel. We currently display the answers in fraction format, which takes a lot of vertical space. Here's an example of what that currently looks like:

![screenshot_285](https://cloud.githubusercontent.com/assets/3046552/22235132/daf9eed0-e1ba-11e6-87dc-3234442dfc0d.png)

To reduce the height of the Questions panel, we would need to reduce the height of the answers. 

Some alternative ways of displaying the above answers:

(1) Rate in ratio format.

$0.50 : 1 Apple
$5.00 : 10 Apples
$3.00 : 6 Apples
$4.00 : 8 Apples

(2) Rate as a fraction that fits on 1 line.

$0.50 / 1 Apple
$5.00 / 10 Apples
$3.00 / 6 Apples
$4.00 / 8 Apples

(3) Display the actual answer to the question, instead of the rate.

$0.50
$5.00
$3.00
8 Apples

(4) ... or something else?

The advantages to making the double number line wider seem worth the effort to brainstorm how we might make this work.  And I think that we can do this in the 2 shopping screens, and not have to make it full width in the Racing Lab screen.

@arouinfar thoughts?

**Comment by pixelzoom** [comment] 2017-01-24 05:44
Note that this also presumes that we'd relocate the radio buttons, as described in https://github.com/phetsims/unit-rates/issues/139.

**Comment by pixelzoom** [comment] 2017-01-24 05:47
It also might be possible to show the answers in the current (fraction) form if we did _both_ of the following:

(1) Reduce the font size throughout the Questions panel. This is likely to negatively impact usability, especially on mobile devices.

(2) Relocate the Reset All button.  I suspect that this would be controversial/unpopular.

**Comment by arouinfar** [comment] 2017-01-24 17:44
> The advantages to making the double number line wider seem worth the effort to brainstorm how we might make this work. And I think that we can do this in the 2 shopping screens, and not have to make it full width in the Racing Lab screen.

@pixelzoom I agree. As I read your original post, my initial concern was what implications this would have for the Racing Lab screen, so I'm glad to know that we can have a full-width double number line on just the shopping screens.

As for the Questions, I'm not particularly keen on drastically reducing the font size or moving the Reset All button, so I think we should discuss the alternatives proposed in https://github.com/phetsims/unit-rates/issues/140#issue-202729220. I think option (1) or (2)  may possibly work. We decided to show the answer in fraction/ratio form to tie into the Mathematical Quality of Instruction, so I wonder if (1) or (2) would also serve this purpose. However, I believe it's not uncommon for students to have trouble interpreting horizontal fractions (e.g. 2/3), so I think we should discuss this with the team and/or @amanda-phet to get further input.

**Comment by pixelzoom** [comment] 2017-01-24 17:53
Going outside my area of expertise... While educating myself about this domain (rates & unit rate), the majority of references that I consulted discussed ratios at some point. Showing the answers in ratio form might be an opportunity for discussion about how rates can be expressed as either a ratio or fraction.

**Comment by ariel-phet** [comment] 2017-01-24 18:08
@pixelzoom and @arouinfar, I am pretty sure that @amanda-phet is very much not a fan of the horizontal writing of a fraction.  Just some other random ideas:

1. Would a word be wrong? In my head I read the fraction as "2 dollars per apple" or such. 

2. Perhaps with a little re-layout the fractional answer could be put to the right of the question? That creates some i18n concerns, but perhaps is viable?

**Comment by pixelzoom** [comment] 2017-01-24 18:18
@ariel-phet suggested:
> Perhaps with a little re-layout the fractional answer could be put to the right of the question? That creates some i18n concerns, but perhaps is viable?

We'd probably have to sacrifice the check mark too.  But a 'green' answer in the space currently occupied by the check mark would probably serve the same purpose.

If the i18n concern is LTR vs RTL, I'm not concerned - the layout of all PhET panels is currently biases towards LTR.

Something else we'll be sacrificing that I didn't mention previously is the "1" denominator that appears under the "Unit Rate?" question, which was requested in https://github.com/phetsims/unit-rates/issues/48.  I.e.:

![screenshot_130](https://cloud.githubusercontent.com/assets/3046552/22260499/af2b0dd6-e226-11e6-8ab4-0a47f641a429.png)

**Comment by pixelzoom** [comment] 2017-01-24 18:20
@ariel-phet suggested:
>  (1) Would a word be wrong? In my head I read the fraction as "2 dollars per apple" or such.

I'd lean towards "$0.50 per Apple", "$4.00 for 8 Apples", etc.

**Comment by pixelzoom** [comment] 2017-02-06 19:48
For comparison...

This screenshot shows the Shopping Lab screen with markers at integer numbers of Apples.  It feels crowded, and doesn't leave much room for fractional numbers of Apples (markers created with the Editor). 

![screenshot_133](https://cloud.githubusercontent.com/assets/3046552/22663505/1128e330-ec6a-11e6-8b53-d852e3ab3047.png)

Here's the same scenario with the double number line expanded to the full width of the screen.

![screenshot_132](https://cloud.githubusercontent.com/assets/3046552/22663540/36a66682-ec6a-11e6-9d83-4652196ba5f4.png)

**Comment by pixelzoom** [comment] 2017-02-06 19:56
If anyone wants to play around with the narrow vs wide double number line... Here's a dev version:
http://www.colorado.edu/physics/phet/dev/html/unit-rates/1.0.0-dev.41/unit-rates_en.html?showAnswers

Shopping screen has the narrower double number line, Shopping Lab is full width of the screen.

It would be helpful if team members played with this before the next design meeting. @amanda-phet @amyh-phet @ariel-phet @arouinfar @kathy-phet.

**Comment by ariel-phet** [comment] 2017-02-06 20:06
@pixelzoom, in some playing around, the full width DNL seems preferable on the shopping lab screen certainly. Still not sure if we can make it work on the first screen, but it seems there is not impediment to full width on the lab screen

**Comment by amanda-phet** [comment] 2017-02-06 20:18
@ariel-phet I was thinking the same thing. We could play with the layout of the Questions panel some more. I think it would also be fine to have two different widths for the two screens because of the nature of the lab screen.

**Comment by arouinfar** [comment] 2017-02-06 20:48
@pixelzoom I don't see any reason why we wouldn't want the full-width double number line on the Shopping Lab screen. 

For the Shopping screen, I think we have some pedagogical limitations that make a shorter Questions panel challenging, but we can discuss the alternatives during design meeting. I don't believe minor markers will be a huge issue here, either. We have not designed the questions so that minor markers will have much pedagogical value. Students in the preliminary interviews did not create any minor markers, though they did use the marker editor quite a bit.

**Comment by amyh-phet** [comment] 2017-02-06 20:50
@pixelzoom   I agree that the full width DNL on the Shopping Lab screen is helpful.  I think the shorter DNL on the Shopping screen is okay and it sounds like it didn't pose issues when @arouinfar  interviewed.

**Comment by pixelzoom** [comment] 2017-02-06 20:56
@arouinfar said:
> For the Shopping screen, I think we have some pedagogical limitations that make a shorter Questions panel challenging, but we can discuss the alternatives during design meeting.  ...

That discussion will be most productive/efficient if:

(a) Team members propose alternatives _before_ the meeting.  I've proposed 5 alternatives, @ariel-phet has proposed 2.  Others?..

(b) Team members weigh in on the alternatives proposed in this issue.

(c) We have some mockups that demonstrate a few of the alternatives that seem most reasonable.

**Comment by ariel-phet** [comment] 2017-02-06 20:59
@arouinfar the one leaning I have towards full width DNL on the first screen is that really the DNL is in my mind the key representation of this sim, and the questions are meant to drive engagement with the DNL. Perhaps I am wrong in that view, but it seems like the "heart" of the sim.

Another alternative might be - could we figure out some sort of carousel implementation for the questions panel that serves the same objectives (I believe @pixelzoom was open to such a change)

But agreed with @pixelzoom a few mockups of alternatives people thing are reasonable would be good.

**Comment by amyh-phet** [comment] 2017-02-06 21:10
@pixelzoom and @arouinfar    I also think it is important for us to keep the unit rate as a fraction with 1 in the denominator. While the double number line is a key representation, we also want students to learn what a unit rate is, so this representation seems key to me as well.  

As far as writing the wording of $0.50 per apple" instead, I'm not sure that students translate this well into a fraction form of $0.50/1 apple.  I also have seen high school students struggle with horizontal fractions like I just used.

**Comment by amanda-phet** [comment] 2017-02-06 22:02
The current fraction representation is important, as everyone has noted. A carousel is an interesting idea... the downside I see right now is hiding the first question (unit rate) when you might want to use it to answer a question lower down. 

To make more room in the questions panel, could the refresh button be moved? Perhaps up next to the title? Could the panel be moved to the left of the reset-all button so we can use more of that vertical space? I know that seems like a terrible bit of trapped space to the right... Could the reset-all button be moved to the left of the panel to allow the panel to use more of that vertical space?

**Comment by pixelzoom** [comment] 2017-02-06 22:06
@amanda-phet said:
> ... A carousel is an interesting idea... the downside I see right now is hiding the first question (unit rate) when you might want to use it to answer a question lower down.

The unit rate question could always be there, the carousel would be the bottom 3 questions.  ...Which might make it clearer than the current arrangement, where pressing the "Refresh" button has no affect on the top (unit rate) question.

**Comment by pixelzoom** [comment] 2017-02-06 22:07
More brainstorming...  

The Questions panel currently shows 4 questions: unit rate + 3 questions that change when the Refresh button is pressed.  Is it necessary to show 3 such questions, or could the same goals be achieved by showing 2 such questions?

Is it necessary to have the "Questions" title on the accordion box when it's expanded?

Do the Questions need to be in an accordion box? (Do they need to be collapsible?)

**Comment by pixelzoom** [comment] 2017-02-06 22:12
Is it necessary to have the "Questions" title on the accordion box when it's expanded?

**Comment by pixelzoom** [comment] 2017-02-06 22:23
Do the Questions need to be in an accordion box? (Do they need to be collapsible?)

**Comment by kathy-phet** [comment] 2017-02-06 22:29
Collapsible is definitely preferred since we want to be able to simplify if they aren't being used.

**Comment by amyh-phet** [comment] 2017-02-06 23:34
@pixelzoom   If I recall correctly, we intentionally created matched sets of questions to target different strategies students might use to solve the problems.  My guess is that reducing the number of challenges would not support these strategies well.

**Comment by arouinfar** [comment] 2017-02-07 00:11
Thank you all for your suggestions!

* The Questions panel should remain collapsable, because as @kathy-phet mentioned, there could be situations in which the questions aren't being used. Perhaps a teacher is demoing the sim at the front of the room, or has designed their own prompts/activity for students to use. 
* The word "Questions" does not need to be visible while the panel is open. This will buy us a little space.
* One drawback of a carousel is that it may encourage students to work through all four sets of prompts, which I don't think is the desired flow. I'd rather have students explore a different item with a different unit rate.
* Each set of questions is scaffolded, with strategies in mind that would leverage answers to earlier prompts. I don't think it's ideal to not have all prompts visible at once (particularly on Veggies and Candy where there are prompts outside of the range of the DNL). 

I will work on some mockups tomorrow and paste them into the issue.

**Comment by arouinfar** [comment] 2017-02-16 00:50
Actually, I think we'll be able to have our cake and eat it too...

I started with screenshots of the latest dev and extended the double number line across the full width of the screen. I was able to compress the contents in the Questions panel while keeping the answers in fraction format. I didn't change the size of any of the text, buttons, etc. -- only the relative spacing. While things in the Questions panel are a bit cozier, I don't think it looks unreasonably crowded.

![image](https://cloud.githubusercontent.com/assets/8419308/23001906/d79d48c6-f3a4-11e6-8f01-058093cfcd0d.png)

![image](https://cloud.githubusercontent.com/assets/8419308/23001915/e372a786-f3a4-11e6-8fdc-483c688d858b.png)

**Comment by arouinfar** [comment] 2017-02-16 00:53
I should also mention that I moved the Reset All button down a few pixels to re-center it between the Questions panel and the navbar.

**Comment by arouinfar** [comment] 2017-02-16 21:26
Discussed in 2/16 design meeting.

* Tighten up vertical space in Questions panel
* Reduce the amount of negative space above the double number line by about 1/2 to give Questions panel a bit more room.

**Comment by pixelzoom** [comment] 2017-02-17 00:29
Done in http://www.colorado.edu/physics/phet/dev/html/unit-rates/1.0.0-dev.55/unit-rates_en.html?showAnswers&randomEnabled=false.

The Questions panel still needs some pixel polishing (see https://github.com/phetsims/unit-rates/issues/152), but it has plenty of room.

@arouinfar please review, feel free to close.

**Comment by arouinfar** [comment] 2017-02-17 19:39
Looks good @pixelzoom. I'll go ahead and close this issue. We can track pixel polishing in a separate issue if need be.

**Closed as completed by arouinfar** 2017-02-17 19:39 UTC
Labels: status:ready-for-review
