### ISSUE TITLE
NumberLineNode: Cannot read property 'indexOf' of undefined

### ISSUE THREAD

**Issue by phet-steele** [phetsims/unit-rates#135] opened 2016-10-25 17:55 UTC
```
TypeError: Cannot read property 'indexOf' of undefined
    at NumberLine.removeMarker (http://phettest.colorado.edu/unit-rates/js/common/model/URNumberLine.js?bust=1477417887730:122:31)
    at NumberLineNode.removeMarkerNode (http://phettest.colorado.edu/unit-rates/js/common/view/URNumberLineNode.js?bust=1477417887730:295:23)
    at NumberLineNode.updateMarkerNode (http://phettest.colorado.edu/unit-rates/js/common/view/URNumberLineNode.js?bust=1477417887730:476:14)
    at http://phettest.colorado.edu/unit-rates/js/common/view/URNumberLineMarkerNode.js?bust=1477417887730:121:14
    at Array.listener (http://phettest.colorado.edu/axon/js/Multilink.js?bust=1477417887730:40:18)
    at Emitter.emit2 (http://phettest.colorado.edu/axon/js/Emitter.js?bust=1477417887730:139:49)
    at Property._notifyObservers (http://phettest.colorado.edu/axon/js/Property.js?bust=1477417887730:167:29)
    at Property._setAndNotifyObservers (http://phettest.colorado.edu/axon/js/Property.js?bust=1477417887730:155:14)
    at Property.set (http://phettest.colorado.edu/axon/js/Property.js?bust=1477417887730:123:16)
    at Property.set value [as value] (http://phettest.colorado.edu/axon/js/Property.js?bust=1477417887730:196:36)
```

**Comment by phet-steele** [comment] 2016-10-25 17:56
Related to #97?

**Comment by pixelzoom** [comment] 2016-10-25 18:00
Yes, another problem with NumberLineNode.  To reproduce:
- start sim
- go to Shopping screen
- put some items on the scale
- switch from fruit to vegetables to fruit
- the "reset marker" button mysteriously appears on the number line, see screenshot below
- press the "reset marker" button and the reported error occur

NumberLineNode will be reimplemented at some point, but I'll leave this issue open until that happens.

![screenshot_59](https://cloud.githubusercontent.com/assets/3046552/19697929/943cec24-9aaa-11e6-8ec7-b18c4aa573d8.png)

**Comment by pixelzoom** [comment] 2017-01-20 18:23
NumberLineNode has been moved to OLDNumerLineNode, and replaced with DoubleNumberLineNode (which does not exhibit this problem).   No plans to fix OLDNumerLineNode, since it will eventually be deleted.  Closing as "will not fix".

**Closed as completed by pixelzoom** 2017-01-20 18:23 UTC
Labels: type:bug, type:wontfix
