### ISSUE TITLE
use FontAwesomeNode

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/unit-rates#123] opened 2016-10-05 20:00 UTC
In https://github.com/phetsims/unit-rates/issues/122#issuecomment-251780449, @arouinfar said:

> There are four items that come from FontAwesome, which is open source.
> - edit-button.png
> - refresh-button.png
> - remove-button.png
> - undo-button.png

We should use FontAwesomeNode for these, not duplicate them as PNG files.

**Comment by pixelzoom** [comment] 2016-10-05 20:53
TODO: Replace with a FontAwesomeNode, remove PNG file and license.json entry for:
- [x] edit-button.png
- [x] refresh-button.png
- [x] remove-button.png
- [x] undo-button.png

**Comment by pixelzoom** [comment] 2016-10-05 21:15
@arouinfar The fontawesome icon for 'undo' looks significantly different than undo-button.png.  

fontawesome 'undo':
![screenshot_41](https://cloud.githubusercontent.com/assets/3046552/19131903/880c93ec-8b0e-11e6-91bf-896a4dd97d88.png)

undo-button.png:
![screenshot_42](https://cloud.githubusercontent.com/assets/3046552/19131910/90c3d5d6-8b0e-11e6-8af5-d70e6202d30c.png)

Recommended to use the fontawesome icon.

[EDIT: FYI, undo-button.png looks like fontawesome 'reply', see http://fontawesome.io/icon/reply/)

**Comment by pixelzoom** [comment] 2016-10-05 21:19
I should have been able to use scenery-phet.RefreshButton for refresh, but it has problems, see https://github.com/phetsims/scenery-phet/issues/269. I also discovered that sun.FontAwesomeNode doesn't  yet support 'refresh'. So I will investigate fixing that, and/or importing the fontawesome 'refresh' icon data into FontAwesomeNode.

**Comment by pixelzoom** [comment] 2016-10-05 21:22
@arouinfar fontawesome 'remove' is an alias for 'times' (see http://fontawesome.io/icon/times/) and looks like this:

![screenshot_43](https://cloud.githubusercontent.com/assets/3046552/19132116/603db426-8b0f-11e6-8bba-336471973f70.png)

Nothing like remove-button.png:

![screenshot_44](https://cloud.githubusercontent.com/assets/3046552/19132133/6fa1aac6-8b0f-11e6-99e2-46b6e3b28e97.png)

Do you recall which fontawesome icon was copied for remove-button.png? I don't see it at http://fontawesome.io/icons/.

**Comment by pixelzoom** [comment] 2016-10-05 21:31
fontawesome 'left-down' might be a nice alternative to remove-button.png.  See http://fontawesome.io/icon/level-down/, it looks like this:

![screenshot_45](https://cloud.githubusercontent.com/assets/3046552/19132447/ae0da1e2-8b10-11e6-83ee-960cbc7abc39.png)

... and could be easily reflected about the y-axis so that the button can stay on the left of the scale.

**Comment by pixelzoom** [comment] 2016-10-05 21:42
@arouinfar To summarize, here's what I need from you to complete this issue:

(1) Is the fontawesome 'undo' icon acceptable or do you want to use the fontawesome 'reply' icon? (see https://github.com/phetsims/unit-rates/issues/123#issuecomment-251801929)

(2) What fontawesome icon corresponds to remove-button.png? Or would you like to use an alternative like 'left-down'? (see https://github.com/phetsims/unit-rates/issues/123#issuecomment-251803444 and https://github.com/phetsims/unit-rates/issues/123#issuecomment-251805637)

**Comment by arouinfar** [comment] 2016-10-05 21:43
@pixelzoom the FontAwesome environment in Illustrator doesn't have any alt-text to show what the names of these icons are, which is why there discrepancies between what I've used as an "undo" button and fa-undo. It's just a big seemingly-unorganized menu I scroll through until I find something that looks good.
![image](https://cloud.githubusercontent.com/assets/8419308/19132688/06b2e32e-8b12-11e6-9e8a-f78e3933bd09.png)

That said, I'm fine with swapping out the undo button for fa-undo.  

I know for a fact that I did not draw the remove arrow... but I'm still looking for it in FontAwesome. I don't particularly like left-down, so I'm looking for alternatives. I'll get back to you shortly.

**Comment by arouinfar** [comment] 2016-10-05 21:48
Ah, I think I've found it. The remove-button isn't from FontAwesome (my bad). I found it in our common component .ai file, which means it's probably in scenery (or sun?).

![image](https://cloud.githubusercontent.com/assets/8419308/19132904/fc69c940-8b12-11e6-963b-e73712d94235.png)

**Comment by pixelzoom** [comment] 2016-10-05 21:49
When you hover over a character in the Glyphs panel, its Unicode value appears to the right of the "Show:" combo box.  In your screenshot it's 'U+f0c4':

![screenshot_47](https://cloud.githubusercontent.com/assets/3046552/19132948/328a46c6-8b13-11e6-92f4-d7f3f6777b30.png)

If you locate the icon, provide me with the Unicode value, and I should be able to locate it.

**Comment by pixelzoom** [comment] 2016-10-05 21:51
@arouinfar said:

> I found it in our common component .ai file

Where does this file live in GitHub? And if it's not in GitHub, it should be.

**Comment by pixelzoom** [comment] 2016-10-05 21:52
I would expect to find this .ai file, or a corresponding png file or button, in scenery-phet. No sign of them.

**Comment by arouinfar** [comment] 2016-10-05 21:56
@pixelzoom it's an ever-evolving .ai file where the designers dump components that are used across sims. There are some general controls like buttons, but also some more specific items like the bike pump. The idea is that AH, AM, and I don't want to have to constantly ask one another for .ai assets, so they live in a common .ai file on Google Drive under PhET Ai Files > Design Assets > Common Components.ai. 

We can put it up on GitHub, but version control would be a nightmare since we regularly add components to the .ai file, and none of the designers have the ability to check files in and out of GitHub.

**Comment by pixelzoom** [comment] 2016-10-05 21:56
The closest thing to the "common component .ai file" is the scenery-phet demo application, which is supposed to serve as a visual guide to PhET-specific UI components.  Run version [1.0.0-dev.15](http://www.colorado.edu/physics/phet/dev/html/scenery-phet/1.0.0-dev.15/scenery-phet_en.html) and navigate to the "Buttons" screen. You'll see this, with the "remove" button notably missing:

![screenshot_49](https://cloud.githubusercontent.com/assets/3046552/19133206/53d494b6-8b14-11e6-9ef8-db73c0e285ad.png)

**Comment by arouinfar** [comment] 2016-10-05 21:59
I guess the remove button was designed for something many, many moons ago and it never made its way into a published sim, but it ended up in the common components .ai file. We can continue to use remove-button.png as is, but I don't know who should get the credit for it. Possibly AM, possibly Bryce. All I know is that it predates me.

**Comment by arouinfar** [comment] 2016-10-05 22:04
To summarize
- Swap undo-button.png for fa-undo 
  ![image](https://cloud.githubusercontent.com/assets/8419308/19133375/2ce42ca8-8b15-11e6-9184-fe7013aadbc6.png)
- Keep remove-button.png as is, but find the appropriate person to credit.
  ![image](https://cloud.githubusercontent.com/assets/8419308/19133386/354a0d0e-8b15-11e6-8995-fef0a7d49b4f.png)

**Comment by pixelzoom** [comment] 2016-10-05 22:05
Since this icon is not currently used in any sims, we have options:

(1) Choose a fontawesome icon as a suitable replacement, so we don't have to develop and maintain this icon.

(2) Implement scenery-phet.RemoveButton, put remove-button.ai and remove-button.png in scenery-phet, use RemoveButton in unit-rates.

Sounds like you want to do (2).

**Comment by arouinfar** [comment] 2016-10-05 22:12
Affirmative, @pixelzoom. I believe (2) is the better option, but before you get started on that I want to confirm that other designers are using it. If it's not being used elsewhere, then (1) is probably the way to go.

@amanda-phet @amyh-phet we currently have this button in the common components .ai file, but it is not actually a scenery component. Do either of you use this button in your mockups, or know of any sims in the works (other than Unit Rates) that use this button?

![image](https://cloud.githubusercontent.com/assets/8419308/19133588/44d79baa-8b16-11e6-8d22-0c905d67e67d.png)

**Comment by ariel-phet** [comment] 2016-10-05 22:14
@arouinfar that button comes from the "undo" button in build a fraction I believe

**Comment by amanda-phet** [comment] 2016-10-05 22:14
There is a similar remove button in Build a Fraction, so perhaps it was a component in java sims that turned into an HTML5 version during a sim design that never made it to development. 

Also, it is possible for us to check in ai files to github, but as @arouinfar said, it would be a nightmare for a file that we are constantly editing. The intention is to have a file with illustrator versions of components that are used in HTML5 sims so that we do not need to redraw them for new mockups. We don't always know the source of the components, but when we draw something for a sim that could be useful in another sim, we add it to the file.

**Comment by pixelzoom** [comment] 2016-10-05 22:17
An undo button next to the scale might also serve the same purpose.

**Comment by amyh-phet** [comment] 2016-10-05 22:21
@arouinfar  I do not have plans for the button in any of the sims I'm currently working on, but I would imagine it could be useful in future sim design.  I don't see  a similar fa icon.

**Comment by arouinfar** [comment] 2016-10-05 22:28
Thanks @ariel-phet @amanda-phet @amyh-phet.

@pixelzoom We originally wanted to keep the undo button and "clear scale"/remove button distinct from one another, since they function differently. The remove button clears the items from the scale, but doesn't really behave like an undo button. For example, if I place three bags on the scale, I would expect an undo button to remove one bag at a time. The remove button would remove all three bags in one go.

@ariel-phet do you think it would be worthwhile to move the remove button to scenery? It looks like Unit Rates and Build a Fraction are the only sims in which it appears, so I'm not sure that it's worth it. @pixelzoom has proposed an alternative FontAwesome icon, level-down (which could be reflected).
![image](https://cloud.githubusercontent.com/assets/8419308/19134006/8da82690-8b18-11e6-81cf-99a1ef28a629.png)

**Comment by ariel-phet** [comment] 2016-10-06 05:34
@arouinfar - if you want to use a different button in unit rates that is fine with me. What you are calling the "remove" button was certainly thought of as an "undo" button in Build a Fraction, and I would like the look we have when we get to Build a Fraction (which will...ehemmm....be a while). So in the meantime, if there is a fontawesome button you think does that trick here, that is fine with me (the reflected choice @pixelzoom suggested seems to convey the message of returning to the shelf well).

**Comment by arouinfar** [comment] 2016-10-06 17:44
Thanks @ariel-phet. Let's reserve the so-called "remove" button for undo applications in future sims. @pixelzoom let's move forward with a FontAwesome icon.  We could either reflect level-down (left) about the y-axis or rotate level-up (right) by 180 degrees. Your call @pixelzoom.
![image](https://cloud.githubusercontent.com/assets/8419308/19163463/4d841ae6-8bb9-11e6-949c-cc28a881955b.png)  ![image](https://cloud.githubusercontent.com/assets/8419308/19163496/69d9959a-8bb9-11e6-90d8-19cd93924900.png)

Here's what the updated button would like. The dimensions of the button have not changed.
![image](https://cloud.githubusercontent.com/assets/8419308/19163674/28c8a2a2-8bba-11e6-8779-cfebc02005f4.png)

**Comment by pixelzoom** [comment] 2016-10-06 19:22
Notes to self about remove-from-scale button:

• use fontawesome 'level-down' icon, f149, http://fontawesome.io/icon/level-down/
• reflect about the y-axis
• 'level-down' icon is apparently newer than sherpa/lib/fontawesome-webfont-3.0.2.svg, so I'll need to upgrade that

**Comment by pixelzoom** [comment] 2016-10-06 19:23
Another note to self: 'level-down' icon is apparently newer than sherpa/lib/fontawesome-webfont-3.0.2.svg, so I'll need to upgrade that.

**Comment by pixelzoom** [comment] 2016-10-07 16:49
We have 2 svg files in sherpa:

```
sherpa/lib/fontawesome-webfont-3.0.2.svg
sherpa/lib/font-awesome-4.5.0/fonts/fontawesome-webfont.svg
```

FontAwesomeNode documentation says:

```
To add a new icon:
// (1) Look up the unicode for the icon you want. For instance: http://fortawesome.github.io/Font-Awesome/icon/camera/ says Unicode: f030
// (2) Navigate to sherpa/lib/fontawesome-webfont-3.0.2.svg and copy the text from the d="" declaration from the corresponding element.
```

@samreid  Why do we need fontawesome-webfont-3.0.2.svg? Why can we just use font-awesome-4.5.0/fonts/fontawesome-webfont.svg?

**Comment by pixelzoom** [comment] 2016-10-07 16:50
... and font-awesome-4.5.0/fonts/fontawesome-webfont.svg contains the icon that I need ('level-down' f149).

**Comment by pixelzoom** [comment] 2016-10-07 17:01
Moved the issue of multiple SVG files to https://github.com/phetsims/sun/issues/271.  In the meantime, I grabbed the SVG data that I needed for 'level-down' from font-awesome-4.5.0/fonts/fontawesome-webfont.svg.

**Comment by pixelzoom** [comment] 2016-10-07 17:02
@arouinfar All of these icons have been converted to font awesome. Please review in master.

**Comment by arouinfar** [comment] 2016-10-07 17:24
Icons look good @pixelzoom. Closing.

**Closed as completed by arouinfar** 2016-10-07 17:24 UTC
Labels: design:general
